app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from app import db
from app.models import Post
from app.posts.forms import PostForm
posts = Blueprint('posts', __name__)


@posts.route("/post", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', form=form, legend='New Post')


@posts.route("/post <int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post)


@posts.route("/post <int:post_id> update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', form=form, legend='Update Post')


@posts.route("/post <int:post_id> delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from app import db, bcrypt
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from app.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template("register.html", title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You have logged in successfully.', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('login unsuccessful.please check your Email and password', 'danger')
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template("account.html", image_file=image_file, form=form)


@users.route('/user <string:username>', methods=['GET', 'POST'])
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("user_posts.html", posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)


@users.route("/contact", methods=["GET", "POST"])
@login_required
def contact():
    return render_template("contact.html")

app/templates/account.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section" xmlns="http://www.w3.org/1999/html">
    <div class="container " style="width:400px">
       <img style="padding-top: 15px;" class="card-img-top img-circle" src="{{ image_file }}" alt="Card image">
       <div class="card-body">
         <h2 class="card-title">{{  current_user.username }}</h2>
         <h5 class="card-text"> {{current_user.email}}</h5>
       </div>
    </div>
     <div class="container jumbotron" style="margin-bottom: 2em; margin-top: 2em;border: 1px solid #b9def0">
        <form  style="padding: 30px;" method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend  style="text-align: center" class="container">Account Info</legend>

                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}
                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.picture.label() }}
                     {{ form.picture(class="form-control-file") }}
                     {% if form.picture.errors %}
                         {% for error in form.picture.errors %}
                     <span class="text-danger">{{ error }}</span></br>
                         {% endfor %}
                     {% endif %}
                 </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class='btn btn-success') }}
                </div>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/contact.html
{% extends 'layout.html' %}
{% block content %}
      <section class="banner">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <h2 style="color: white"> Welcome to my contact page</h2>
                     <p>You Can Click On The Button Below To Send Me An Email.</p>
                     <p>OR</p>
                     <h4><p>Contact Me On <a href="tel: +2348124941387 ">+ 234 812 494 1387</a></p></h4>
                     <button><a href="mailto:eorji452@gmail.com">Send An Email</a></button>
                     <div class="primary-button">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

app/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}

     <div class="container justify-center jumbotron " data-aos="zoom-in" style="margin-bottom: 2em; margin-top: 2em;border:1px solid #b9def0">
        <form style="padding: 20px " method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend style="text-align: center" class="container" >{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class='form-control-label') }}
                    {% if form.title.errors %}
                        {{ form.title(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.title(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.content.label(class='form-control-label') }}
                    {% if form.content.errors %}
                        {{ form.content(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.content(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
                <div class="form-group ">
                    {{ form.submit(class='btn btn-primary') }}
                </div>
        </form>
    </div>
{% endblock content %}

app/templates/index.html
{% extends 'layout.html' %}
{% block content %}
  {% for post in posts.items %}
    <br>
    <article class="containerr " style="border: 1px solid black; width: 100%; display: flex; padding-top: 10px; padding: 20px">
      <img class="rounded-circle img-circle"  src="{{url_for('static', filename='img/' + post.author.image_file) }}" height="60" width="60">
      <div class="media-body" style="padding-left: 8px">
        <div class="article-metadata" style="border-bottom:1px solid silver">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{post.author.username}}</a>
          <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
        </div>
        <h3><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{post.title}}</a></h3>
<!--        <p class="article-content" >{{post.content}}</p>-->
          <a href="{{ url_for('posts.post', post_id=post.id) }}">Read the contents >>></a>
      </div>
    </article>
{% endfor %}
<hr>
<div class="container" style="width: 50%">
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
           <a style="align-items: center" class=" btn btn-success mb-4 " href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a style="align-items: center; border:1px solid silver" class=" btn btn-outline-info mb-4 " href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
  {% else %}
       ...
    {% endif %}
{% endfor %}
</div>
<hr>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!--
Victory HTML CSS Template
https://templatemo.com/tm-507-victory
-->
        <title>Emmanuel's blog</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="static/css/bootstrap.min.css">
        <link rel="stylesheet" href="static/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="static/css/fontAwesome.css">
        <link rel="stylesheet" href="static/css/hero-slider.css">
        <link rel="stylesheet" href="static/css/templatemo-style.css">
        <link rel="stylesheet" href="static/css/owl-carousel.css">


    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="../static/js/config.js"></script>

        <link href="https://fonts.googleapis.com/css?family=Spectral:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

        <script src="static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>

<body>
    <div class="header">
        <div class="container">
            <a href="#" class="navbar-brand scroll-top">Emmanuel</a>
            <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                    <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!--/.navbar-header-->
                <div id="main-nav" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('main.index') }}">Home</a></li>
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('posts.new_post') }}">New Post</a></li>
                        <li><a href="{{ url_for('users.contact') }}">Contact Me</a></li>
                        <li><a href="{{ url_for('users.account')}}">Account</a> </li>
                        <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('users.register') }}">Register</a></li>
                        {% endif %}


                    </ul>
                </div>

            </nav>

        </div>

    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
             {% for category, message in messages %}
                 <div class="alert alert-{{ category }}">
                     {{ message }}
                 </div>
             {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock content %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <p>Copyright &copy; 2022 Emmanuel Template</p>
                </div>
                <div class="col-md-4 ">
                    <ul class="social-icons">
                        <li><a rel="nofollow" href="https://free.facebook.com/home.php?ref_component=mfreebasic_home_header&ref_page=%2Fwap%2Fhome.php&refid=7"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <p>Design: Emmanuel</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="static/https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="static/js/vendor/bootstrap.min.js"></script>

    <script src="static/js/plugins.js"></script>
    <script src="static/js/main.js"></script>
    <script src="//cdn.ckeditor.com/4.6.2/basic/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('editor')
    </script>

    <script type="text/javascript">
    $(document).ready(function() {
        // navigation click actions
        $('.scroll-link').on('click', function(event){
            event.preventDefault();
            var sectionID = $(this).attr("data-id");
            scrollToID('#' + sectionID, 750);
        });
        // scroll to top action
        $('.scroll-top').on('click', function(event) {
            event.preventDefault();
            $('html, body').animate({scrollTop:0}, 'slow');
        });
        // mobile nav toggle
        $('#nav-toggle').on('click', function (event) {
            event.preventDefault();
            $('#main-nav').toggleClass("open");
        });
    });
    // scroll function
    function scrollToID(id, speed){
        var offSet = 0;
        var targetOffset = $(id).offset().top - offSet;
        var mainNav = $('#main-nav');
        $('html,body').animate({scrollTop:targetOffset}, speed);
        if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
        }
    }
    if (typeof console === "undefined") {
        console = {
            log: function() { }
        };
    }
    </script>
<!--<script>       -->
<!--    import * as CKEDITOR -->
<!--        from "../../../../AppData/Local/Programs/Python/Python39/Lib/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp";-->
<!--</script>-->
</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}
{% block content %}

<div class="preloader">
     <div class="sk-spinner sk-spinner-wordpress">
          <span class="sk-inner-circle"></span>
     </div>
</div>

    <div class="container justify-center jumbotron " data-aos="zoom-in" style="margin-bottom: 2em; margin-top: 2em;border:1px solid #b9def0">
        <form style="padding: 20px " method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend style="text-align: center" class="container" >Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-input-label") }}
                </div>
            </fieldset>
                <div class="form-group ">
                    {{ form.submit(class='btn btn-primary') }}
                </div>
            <h5 class="text-muted ml-2">
                <a  href="{{ url_for('users.reset_request') }}" >Forgot Password?</a>
            </h5>
        </form>
        <h4>
            Need an account? <a href="{{ url_for('users.register') }}" >Sign Up</a>
        </h4>
    </div>

{% endblock content %}

app/templates/post.html
{% extends 'layout.html' %}
{% block content %}
    <br>
    <article class="containerr " style="border: 1px solid black; width: 100%; display: flex; padding-top: 10px; padding: 20px">
      <img class="rounded-circle img-circle" style=" " src="{{url_for('static', filename='img/' + post.author.image_file) }}" height="60" width="60">
      <div class="media-body" style="padding-left: 8px">
        <div class="article-metadata" style="border-bottom:1px solid silver">
          <a class="mr-2" href="#">{{post.author.username}}</a>
          <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            {% if post.author == current_user %}
               <div>
                   <a class="btn btn-success btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                   <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal" >Delete</button>
               </div>
            {% endif %}
        </div>
        <h2>{{post.title}}</h2>
        <p class="article-content">{{post.content}}</p>
      </div>
    </article>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
     aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button  type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">Are you sure that you want to delete this post?</span>
                </button>
            </div>
<!--            <div class="media-body"></div>-->
            <div class="modal-footer" style="display: flex; ">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                </button>
                <br>
                <form style="padding-left: 20px" action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock content %}

app/templates/register.html
{% extends 'layout.html' %}
{% block content %}

<div class="preloader">
     <div class="sk-spinner sk-spinner-wordpress">
          <span class="sk-inner-circle"></span>
     </div>
</div>

    <div class="container justify-center jumbotron " data-aos="zoom-in" style="margin-bottom: 2em; margin-top: 2em;border:1px solid #b9def0">
        <form  style="padding: 20px;" method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend style="text-align: center" class="container" >Join Today</legend>

                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}
                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirm_password.label(class='form-control-label') }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{ form.confirm_password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

            </fieldset>
                <div class="form-group ">
                    {{ form.submit(class='btn btn-primary') }}
                </div>
        </form>
        <h4>
            Already have an account? <a href="{{ url_for('users.login') }}" >Login</a>
        </h4>
    </div>

{% endblock content %}

app/templates/user_posts.html
{% extends 'layout.html' %}
{% block content %}
<div style="width: 50%" class="container">
     <h1>Post by {{ user.username }} ({{ posts.total }})</h1>
</div>

  {% for post in posts.items %}
    <br>
    <article class="containerr " style="border: 1px solid black; width: 100%; display: flex; padding-top: 10px; padding: 20px">
      <img class="img-circle" style=" " src="{{url_for('static', filename='img/' + post.author.image_file) }}" height="60" width="60">
      <div class="media-body" style="padding-left: 8px">
        <div class="article-metadata" style="border-bottom:1px solid silver">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{post.author.username}}</a>
          <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
        </div>
        <h3><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{post.title}}</a></h3>
        <p class="article-content">{{post.content}}</p>
      </div>
    </article>
{% endfor %}
<hr>
<div class="container" style="width: 50%">
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
           <a style="align-items: center" class=" btn btn-success mb-4 " href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a style="align-items: center; border:1px solid silver" class=" btn btn-outline-info mb-4 " href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
  {% else %}
       ...
    {% endif %}
{% endfor %}
</div>
<hr>
{% endblock content %}